version: '2'
services:
  kiosk:
    build: ./chromium-kiosk
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
    environment:
      - LAUNCH_URL=http://your-xibo-cms-url
